// <auto-generated />
using System;
using AgendaMvc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AgendaMvc.Migrations
{
    [DbContext(typeof(AgendaMvcContext))]
    [Migration("20201006223932_Actualization")]
    partial class Actualization
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AgendaMvc.Models.Contatos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<string>("Tel");

                    b.Property<int?>("TipoContatoId");

                    b.HasKey("Id");

                    b.HasIndex("TipoContatoId");

                    b.ToTable("Contatos");
                });

            modelBuilder.Entity("AgendaMvc.Models.TipoContato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("TipoContato");
                });

            modelBuilder.Entity("AgendaMvc.Models.Contatos", b =>
                {
                    b.HasOne("AgendaMvc.Models.TipoContato", "TipoContato")
                        .WithMany("Contato")
                        .HasForeignKey("TipoContatoId");
                });
#pragma warning restore 612, 618
        }
    }
}
